version: '3.8'

services:
  db:
    image: postgres:16
    container_name: pet_adoption_db
    environment:
      POSTGRES_USER: petuser
      POSTGRES_PASSWORD: petpass
      POSTGRES_DB: pet_adoption
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
